services:
  - type: web
    name: front-pyments
    runtime: static
    buildCommand: npm install && npm run build
    static:
      publishDirectory: dist
      routes:
        - type: rewrite
          source: /*
          destination: /index.html
